### ISSUE TITLE
Deprecated methods in Swift 4.1

### ISSUE THREAD

**Issue by neilsardesai** [tonyarnold/Differ#19]
Hey @tonyarnold, just wanted to let you know that Xcode 9.3 (just released today) ships with Swift 4.1, and is warning of several deprecated methods used in Differ.

<img width="314" alt="screen shot 2018-03-29 at 8 47 05 pm" src="https://user-images.githubusercontent.com/4098825/38121078-acacf574-3392-11e8-9c15-ceb77b384a52.png">

**Comment by tonyarnold** [comment]
Thanks, Neil. I’ll fix these tonight when the kids are in bed.

**Comment by neilsardesai** [comment]
No rush. Thanks so much for working on this project; it’s pretty awesome!

**Comment by tonyarnold** [comment]
Hi Neil, I've just published Differ 1.1.0, which is compatible with Swift 4.1/Xcode 9.3 and fixes these warnings. Thanks for being patient!

**Comment by neilsardesai** [comment]
🙌
