### ISSUE TITLE
Generic parameter 'T' could not be inferred

### ISSUE THREAD

**Issue by Sully73** [tonyarnold/Differ#3]
Is there a way to make the following situation work.

I have an enum as follows

```
public enum PlaylistItem {
    case previous(Video)
    case current(Video)
    case next(Video)
}
```
The datasource for the collectionView is an Array of the PlaylistItem enum, when I attempt to animate changes I get  `Generic parameter 'T' could not be inferred`
```
 let newPlayList: [PlaylistItem] = [.current(Video(id: "123"))]
 let oldPlayList: [PlaylistItem] = [.previous(Video(id: "12334")), .current(Video(id: "1234453"))]
 self?.mixCollectionView.animateItemChanges(oldData: oldPlayList, newData: newPlayList)
```

Is there any way I can make this work?

**Comment by Sully73** [comment]
Sorry never mind, I had to make the enum conform to equatable

**Comment by tonyarnold** [comment]
Glad you figured it out! Could the comments/documentation here have been clearer somehow? I'm keen to improve it if possible.

**Comment by electic** [comment]
Hi,

I am having the same problem. I have an array of News objects:

`import Foundation

enum NewsType {
    case news
    case chat
    case unkonwn
}

class News : Equatable {
    var title : String = "--"
    var link : URL!
    var createdAt : Date?
    var type : NewsType = NewsType.unkonwn
    var author : String = ""
}

func ==(lhs: News, rhs: News) -> Bool {
    return lhs.link == rhs.link
}
//------------------------------------------------------------------------------------
`

However, I get the same error. There doesn't seem to be anything in the docs but a very very basic example. Can someone help?

**Comment by tonyarnold** [comment]
Hi @electic, can you put this into an example project showing the problem? I'd be happy to have a look when you have.
