### ISSUE TITLE
Crash when inserting items into empty collection view

### ISSUE THREAD

**Issue by neilsardesai** [tonyarnold/Differ#30]
Hey @tonyarnold, the latest version of Differ is causing a crash when inserting items into an empty collection view. Specifically, the crash started with commit 9db06bbd85c91b26f1fb15d7f970670aa359f2c5 (Use array literals to provide IndexPaths for compatibility with Swift Package Manager).

This crash did not occur prior to this commit.

I’ve attached sample projects, one using Differ as of commit 30d9b35a51d022a9c2fa2303884b57c990ed3a25 (no crash) and one using commit 9db06bbd85c91b26f1fb15d7f970670aa359f2c5 (crashes).

Tested using Xcode 9.3 and iOS 11.3. 

(Not sure why just using different syntax for IndexPath is causing a crash  ¯\_(ツ)_/¯)

[Differ Crash Sample Projects.zip](https://github.com/tonyarnold/Differ/files/1933758/Differ.Crash.Sample.Projects.zip)

<img width="1129" alt="screen shot 2018-04-20 at 4 37 01 pm" src="https://user-images.githubusercontent.com/4098825/39074946-19f236ee-44b9-11e8-965f-740865b94288.png">

**Comment by tonyarnold** [comment]
It wasn’t the syntax, it was the ordering. Initialising `IndexPath` using an array expects you to specify the path from the root (section) down to the item - I had it inverted. Silly oversight, but if you want to check with 6038fe02e17945e4c54723bf2ced162c18c612b5 it should work now. Thanks for the report!

**Comment by neilsardesai** [comment]
Oh lol, I guess this is why named parameters are awesome 🙈. Confirmed not to crash anymore. Thanks for the quick fix!

**Comment by tonyarnold** [comment]
Named parameters _are_ great, however SwiftPM’s insistence on targeting a four year old macOS SDK release makes it tricky to use them.
