### ISSUE TITLE
Can't compile Differ with Carthage to generate a StaticFramework.

### ISSUE THREAD

**Issue by pablonosh** [tonyarnold/Differ#37]
Following the steps identified here:
https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md

I can't compile Differ to generate a StaticFramework.

`*** Building scheme "Differ" in Differ.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/peter/Carthage/Checkouts/Differ/Differ.xcodeproj -scheme Differ -configuration Release -derivedDataPath /Users/peter/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4_9F1027a/Differ/1.2.3 -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2x/_53hdv7j2ts7yrqbhbjbghgw0000gn/T/Differ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/peter/Carthage/Checkouts/Differ)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2x/_53hdv7j2ts7yrqbhbjbghgw0000gn/T/carthage-xcodebuild.wzz23x.log`

[carthage-xcodebuild.wzz23x.log](https://github.com/tonyarnold/Differ/files/2119769/carthage-xcodebuild.wzz23x.log)

**Comment by tonyarnold** [comment]
Hi, can I get a copy of the build script you used?

**Comment by pablonosh** [comment]
it looks confusing but it's recommended by carthage on 
https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md

then running:

./carthage-build-static.sh Differ

**Comment by pablonosh** [comment]
Hi

I have a fix for this, I just rebuilt the xcode project again, it was quite an old project file and I guess didn't support the latest build settings etc.

I have a branch I'd like to push for a review - can I get permission to push a branch? Alternatively I could send the new project file to you in some way.

Ta

Peter

**Comment by tonyarnold** [comment]
Please see my comments on #38 about this: https://github.com/tonyarnold/Differ/pull/38#issuecomment-424677685
