### ISSUE TITLE
Cocoapods version doesn't support Swift 4.2

### ISSUE THREAD

**Issue by ronsrebro** [tonyarnold/Differ#39]
I'm new to all of this, so this might be silly and stupid.

I'm installing differ from Cocoapods and can't get it to install a version that supports Swift 4.2

The current version on Cocoapods is 1.2.3.

Looking at the code in the repo there was obviously work done to update the codebase to 4.2

Any plans on updating Cocoapods version, or I do I work around it?

**Comment by iDonJose** [comment]
Hi @ronsrebro,

If you want to work with Swift 4.2, you can either :

- Fork this repo and update Differ with Swift 4.2 (this require a little work)

- Or simply keep using Differ with 4.1, by  adding at the end of your pod file :
````
post_install do |installer|

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|

            if ["Differ"].include? target.name
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end

        end
    end
    
end
````

**Comment by tonyarnold** [comment]
@iDonJose's instructions are spot-on. From what I can see, this is a CocoaPods issue.
