### ISSUE TITLE
Cocoapods release for swift 4.2?

### ISSUE THREAD

**Issue by btelintelo** [tonyarnold/Differ#46]

**Comment by frankois944** [comment]
The current version is not working on Swift 4.2

**Comment by frankois944** [comment]
Hello,
the current version on Pod is not compatible with swift 4.2

**Comment by frankois944** [comment]
For waiting the new pod, we can use :

pod 'Differ', git: 'https://github.com/tonyarnold/Differ.git', commit: '6dbd920ade1586460ec492b2baebb4fea92db3c4'

The fix is already done but not published

**Comment by tonyarnold** [comment]
I've just pushed Differ 1.3.0 to CocoaPods, and tagged a release for Carthage. Thanks for the nudge to do this, folks - I'm sorry it took a week longer than it should have.
