### ISSUE TITLE
Differ does not build universal for Apple Silicon Macs

### ISSUE THREAD

**Issue by deborahgoldsmith** [tonyarnold/Differ#72]
Due to the explicit architectures listed in Universal-Target-Base.xcconfig, Differ will not build universal for Apple Silicon Macs.

**Comment by deborahgoldsmith** [comment]
I will be submitting a PR.

**Comment by tonyarnold** [comment]
This is the kind of issue I love to wake up to! Thanks for the PR, @deborahgoldsmith! I'll take care of fixing up the Bitrise CI workflow now.
