### ISSUE TITLE
Can't build in Xcode 12 with Differ as an spm sub-dependency

### ISSUE THREAD

**Issue by jnutting** [tonyarnold/Differ#74]
I have a project using Bond and and Differ, both imported with Xcode's spm integration. When I open this project in Xcode 12, Xcode fails to build, with the following error:

```
error: The package product 'Differ' requires minimum platform version 9.0 for the
 iOS platform, but this target supports 8.0 (in target 'Bond' from project 'Bond')
```

This problem seems to occur because Differ doesn't declare a minimum platform version, which makes Xcode interpret its minimum platform as 9.0 (the new default for Xcode 12), which clashes with what Bond declares in its `Package.swift`:

```
    platforms: [
        .macOS(.v10_11), .iOS(.v8), .tvOS(.v9)
    ],
```

I verified that this problem is not tied to my specific project by creating an entirely new project, adding just the Bond package (which automatically pulls in Differ), and seeing the same error in Xcode 12. I think that adding the same `platforms` declaration that Bond has would solve this problem.

**Comment by tonyarnold** [comment]
This has been done as part of 976e98e28a5febad583cae4d2eefb3d86df5df0d, and these changes will be included in Differ 1.4.6 when it is released. Thanks for reporting the problem, @jnutting!
