### ISSUE TITLE
Throw exception, invalid number of rows

### ISSUE THREAD

**Issue by priore** [tonyarnold/Differ#76]
![Schermata 2021-01-27 alle 13 29 25](https://user-images.githubusercontent.com/1537350/105991259-dab28380-60a3-11eb-8c83-30cbca56665d.jpg)

**Comment by algrid** [comment]
I have a similar crash report for my table view update:

> Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (35) must be equal to the number of rows contained in that section before the update (36), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

Can't reproduce it though.

**Comment by priore** [comment]
it's our mistake because we are try using "animateRowChanges" with a multi-sections dataset but we should use animateRowAndSectionChanges which is right for a multi-section dataset.
