### ISSUE TITLE
Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.5 compiler:

### ISSUE THREAD

**Issue by justdan0227** [tonyarnold/Differ#78]
Is there an update to 5.5?

**Comment by tonyarnold** [comment]
Is something not working for you? There's nothing in the project that doesn't build under Swift 5.5.

**Comment by justdan0227** [comment]
Thanks... so when I try to compile / carthage

*** Downloading Differ binary at "Differ 1.4.5"
***  Skipped installing Differ binary due to the error:
	"Incompatible Swift version - framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.5 (swiftlang-1300.0.27.6 clang-1300.0.27.2)."

**Comment by tonyarnold** [comment]
I've put in a request for macOS 11 access for this project, so that I can actually specify Swift 5.4. 

Once that's done, I'll look at a prerelease using Swift 5.5 and Xcode 13.0-beta. 

In the meantime, you could consider switch Carthage to build the project from source, rather than failing if the binary is missing.

**Comment by justdan0227** [comment]
so is there an update on this.. I'm still getting the following when trying to use XCode13

	"Incompatible Swift version - framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)."

**Comment by tonyarnold** [comment]
Still working on it, sorry - I'd like to switch over to XCFrameworks for the next release, so I've been working on making that automatically happen when I release a new version. 

It's taking a bit longer because I'm short on time (school holidays in a pandemic :sweat_smile:
