### ISSUE TITLE
Broken sources or obsolete readme?

### ISSUE THREAD

**Issue by gerchicov-bp** [tonyarnold/Differ#80]
From your readme:
```
let diff = dataSource.diff(newDataSource)
tableView.apply(diff)
```

It doesn't work because diff is `Diff` but apply method requires `ExtendedDiff` and these 2 classes are incompatible

**Comment by tonyarnold** [comment]
You're correct - the sample in the readme is incorrect. The tableview `apply(…)` methods on both platforms require an `ExtendedDiff`, so it should be: 

```swift
let diff = dataSource.extendedDiff(newDataSource)
tableView.apply(diff)
```

I'll update it as part of the version bump I'm looking at - thanks for reporting this.
